- name: Relaunch containers
  command: dv-launcher --no-color
  args:
    chdir: /opt/odoo
  register: output
  failed_when: false

- name: Show output (success)
  debug:
    var: output.stderr_lines
  when: "'FAILURE LOGS' not in output.stderr and output.rc == 0"

- name: Show output (failed)
  ansible.builtin.fail:
    msg: "{{ output.stderr_lines }}"
  when: "'FAILURE LOGS' in output.stderr or output.rc != 0"
