$ANSIBLE_VAULT;1.1;AES256
64343565383035396334646162383731323039666239653866353334613231636266613735336534
3239383664316332366436316130323538653339336331660a353234373639633436393633386461
30656162363234623637306261666361383161633362646632356264373736366136333864633632
6237613861656433640a366633623161323630323031656632313933663562373231313331373237
30323139613665363435386565383864333138363736383766373761656532373835626438383736
62666231643538386435613036353234656364323231353764643235653233336561303164626637
653934643262656363323934373164376564
