- name: Generate dynamic.yml for each Odoo instance
  template:
    src: dynamic.yml.j2
    dest: "/opt/traefik/config/dynamic/{{ inventory_hostname_short }}.yml"
    mode: '0644'
  delegate_to: "{{ traefik_host }}"
